### PR TITLE
Anshyyy

### PR DESCRIPTION
**Pull request by anshyyy**

### CODE REVIEW

**Comment by aryashah2k** [comment]
Hi, please let me know if you need some issues assigned or something, this PR has been pending for 3 days

**Comment by anshyyy** [comment]
yeah bro actually I was busy in my exams. it will be over today so I'll be back!

**Comment by anshyyy** [comment]
@aryashah2k btw can you assign me 140 to 191 all alphabetic patterns ? or should I comment on manually on every of them?

**Comment by aryashah2k** [comment]
> yeah bro actually I was busy in my exams. it will be over today so I'll be back!

No worries, take your time

**Comment by aryashah2k** [comment]
Do I merge this or you wantr to add more patterns?

**Comment by anshyyy** [comment]
@aryashah2k you can add these for now!

**Review by aryashah2k — APPROVED** [review]

**Pull request merged**
